# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gethook < Formula
  desc "Receive, debug, and replay webhooks locally — in seconds."
  homepage "https://gethook.dev"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gethooklabs/gethook-cli/releases/download/v0.1.1/gethook_darwin_amd64.tar.gz"
      sha256 "ca448ec6c13f7f495af7c66acd7de8c5d8c3e92a35df2b75833e83171bc57d36"

      define_method(:install) do
        bin.install "gethook"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gethooklabs/gethook-cli/releases/download/v0.1.1/gethook_darwin_arm64.tar.gz"
      sha256 "bceb50a4a99f611182ec2147cbd1efbfd1e411922bc4a73a50e8259e44e4cc5f"

      define_method(:install) do
        bin.install "gethook"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gethooklabs/gethook-cli/releases/download/v0.1.1/gethook_linux_amd64.tar.gz"
      sha256 "8ce42fcd4421cbb1ea951927f2db8e2f2245e9d81f85da7f30ab0577d29e3612"
      define_method(:install) do
        bin.install "gethook"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gethooklabs/gethook-cli/releases/download/v0.1.1/gethook_linux_arm64.tar.gz"
      sha256 "df697cfd35497549502179227b590e3f15f8b7caffcdd86599afbdf303e9c4ef"
      define_method(:install) do
        bin.install "gethook"
      end
    end
  end

  test do
    system "#{bin}/gethook version"
  end
end
